let suggestions = [
    "Patna,Bihar",
    "Thiruvananthapuram,Kerala",
    "Panaji,Goa",
    "Jaipur,Rajasthan",
    "Lucknow,Uttar Pradesh",
    "Chandigargh,Punjab",
    "Bengaliuru,Karnataka",
    "Mumbai,Maharastra",
    "Gandhinagar,Gujarat",
    "Chennai,Tamil Nadu",
    "Bhopal,Madhya Pradesh",
    "Amaravati,Andhra Pradesh",
    "Raipur,Chhattisgarh",
    "Gairsain. Dehradun, Uttarakhand",
    "Hyedrabad,Telengana",
    "Chandigarh,Haryana",
    "Kolkata,West Bengal",
    "Dispur,Assam",
    "Bhubaneswar,Odisha",
    "Shimla . Dharamshala , Himachal Pradesh",
    "Ranchi,Jharkhand",
    "Gangtok,Sikkim",
    "Kohima,Nagaland",
    "Imphal,Manipur",
    "Shillong,Meghalaya",
    "Itanagar,Arunachal Pradesh",
    "Agartala,Tripura",
    "Aizawl,Mizoram",
    "Delhi,India",
];
